name: Build & Deploy Windows MSI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Fetch GUI
        uses: actions/checkout@v3
      
      - name: Fetch Release Tags
        run: git fetch --all --tags

      # Fail the build if the version number wasn't incremented
      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: src-tauri/Cargo.toml
          tagFormat: v${version}
        id: version_check_staging
        
      - name: Install Tauri CLI
        run: yarn add -D @tauri-apps/cli

      - name: Build GUI
        env:
          TAURI_PRIVATE_KEY: '${{ secrets.TAURI_PRIVATE_KEY }}'
          TAURI_KEY_PASSWORD: '${{ secrets.TAURI_KEY_PASSWORD }}'
        run: yarn tauri build

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: RLBotGUI Rust port ${{ steps.version_check_staging.outputs.releaseVersion }}
          artifacts: "./**/target/**/*.msi,./**/target/**/*.msi.zip"
          body: ${{ github.event.head_commit.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version_check_staging.outputs.releaseVersion }}
            
      - name: Create & move out new latest.json 
        run: |
          cd src-tauri
          call gen-latest-json.bat ${{ steps.version_check_staging.outputs.releaseVersion }} ${{ github.event.commits[0].message }}
          MOVE /Y latest.json ../../
          
      - name: Change branch to site
        uses: actions/checkout@v3
        with:
          ref: site
          
      - name: Move in new latest.json
        run: MOVE \Y ../latest.json ./docs/
            
      - name: Commit new latest.json
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: latest.json
          commit-message: Updating latest.json to include ${{ steps.version_check_staging.outputs.releaseVersion }}
          ref: refs/heads/site
