name: Build & Deploy Files

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Fetch GUI
        uses: actions/checkout@v3

      - name: Fetch Release Tags
        run: git fetch --all --tags

      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: src-tauri/Cargo.toml
          tagFormat: v${version}
          failBuild: false
        id: version_check_staging

      - name: Fetch build cache
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        uses: actions/cache@v3.0.4
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Tauri CLI
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' && steps.cache.outputs.cache-hit != 'true' }}
        run: yarn add -D @tauri-apps/cli

      - name: Build GUI
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' && steps.cache.outputs.cache-hit != 'true' }}
        env:
          TAURI_PRIVATE_KEY: '${{ secrets.TAURI_PRIVATE_KEY }}'
          TAURI_KEY_PASSWORD: '${{ secrets.TAURI_KEY_PASSWORD }}'
        run: yarn tauri build

      - name: Create Release
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          name: RLBotGUI Rust port ${{ steps.version_check_staging.outputs.releaseVersion }}
          artifacts: "./**/target/**/*.msi,./**/target/**/*.msi.zip"
          body: ${{ github.event.head_commit.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version_check_staging.outputs.releaseVersion }}

      - name: Create new latest.json
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        shell: cmd
        run: gen-latest-json.bat ${{ steps.version_check_staging.outputs.releaseVersion }} ${{ steps.version_check_staging.outputs.rawVersion }} "${{ github.event.head_commit.message }}"

      - name: Change branch to site
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        uses: actions/checkout@v3
        with:
          ref: site

      - name: Move in new latest.json
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        shell: cmd
        run: move ..\latest.json .\docs\

      - name: Commit new latest.json
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        shell: cmd
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs\latest.json
          git commit -m "Updating latest.json to include ${{ steps.version_check_staging.outputs.releaseVersion }}"
          git push

  linux:
    runs-on: ubuntu-18.04
    permissions:
      contents: write
    steps:
      - name: Fetch GUI
        uses: actions/checkout@v3

      - name: Fetch APT repo
        uses: actions/checkout@v3
        with:
          repository: VirxEC/rlbot_gui_rust_apt
          path: rlbot_gui_rust_apt
          token: ${{ secrets.GH_PAT }}

      - name: Check Release Tags
        working-directory: rlbot_gui_rust_apt
        id: version_check_staging
        run: |
          git fetch --all --tags
          cver=$(grep -x "version = ".*"" ../src-tauri/Cargo.toml | head -1)
          cver=${cver#"version = \""}
          cver=${cver%"\""}
          echo '::set-output name=rawVersion::'$cver
          cver=v$cver
          echo '::set-output name=releaseVersion::'$cver
          if [ $(git tag -l "$cver") ]; then
              echo '::set-output name=versionChanged::true'
          else
              echo '::set-output name=versionChanged::false'
          fi

      - name: Fetch build cache
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        uses: actions/cache@v3.0.4
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install ubuntu dev packages
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' && steps.cache.outputs.cache-hit != 'true' }}
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install Tauri CLI
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' && steps.cache.outputs.cache-hit != 'true' }}
        run: yarn add -D @tauri-apps/cli

      - name: Build GUI
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' && steps.cache.outputs.cache-hit != 'true' }}
        run: yarn tauri build

      - name: Move out build files
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        run: mv src-tauri/target/release/bundle/deb/ ./

      - name: Create .tar.gz
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        run: tar -czf linux-basics.tar.gz deb/*/data/usr/bin/rl-bot-gui deb/*/data/usr/share/applications/rl-bot-gui.desktop

      - name: Create Release
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          name: RLBotGUI Rust port ${{ steps.version_check_staging.outputs.releaseVersion }}
          artifacts: "linux-basics.tar.gz,deb/*.deb"
          body: ${{ github.event.head_commit.message }}
          token: ${{ secrets.GH_PAT }}
          tag: ${{ steps.version_check_staging.outputs.releaseVersion }}
          repo: rlbot_gui_rust_apt

      - name: Move in update files
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        working-directory: rlbot_gui_rust_apt
        run: |
          mv ../deb/*.deb apt-repo/pool/main/
          cd apt-repo
          dpkg-scanpackages --arch amd64 pool/ > dists/stable/main/binary-amd64/Packages
          cat dists/stable/main/binary-amd64/Packages | gzip -9 > dists/stable/main/binary-amd64/Packages.gz

      - name: Sign update files
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        working-directory: rlbot_gui_rust_apt
        env: 
          APT_KEY: ${{ secrets.APT_KEY }}
          KEY_NAME: ${{ secrets.KEY_NAME }}
        run: |
          echo "${{ secrets.APT_KEY }}" > pgp-key.private
          chmod +x generate-deb-release-info.sh
          cd apt-repo/dists/stable/
          ../../../generate-deb-release-info.sh > Release
          cd ../../../
          export GNUPGHOME="$(mktemp -d pgpkeys-XXXXXX)"
          gpg --list-keys
          cat pgp-key.private | gpg --import
          cat apt-repo/dists/stable/Release | gpg --default-key ${{ secrets.KEY_NAME }} -abs > ./apt-repo/dists/stable/Release.gpg
          cat apt-repo/dists/stable/Release | gpg --default-key ${{ secrets.KEY_NAME }} -abs --clearsign > ./apt-repo/dists/stable/InRelease

      - name: Commit updates
        if: ${{ steps.version_check_staging.outputs.versionChanged == 'true' }}
        working-directory: rlbot_gui_rust_apt
        run: |
          rm -rf ../.git
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add ${{ steps.version_check_staging.outputs.rawVersion }}"
          git push
