name: Build & Deploy Windows MSI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: src-tauri
    steps:
      - name: Fetch GUI
      - uses: actions/checkout@v3
      
      - name: Fetch Release Tags
        run: git fetch --all --tags

      # Fail the build if the version number wasn't incremented
      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: src-tauri/Cargo.toml
          tagFormat: v${version}
        id: version_check_staging
        
      - name: Install Tauri CLI
        run: cargo install tauri-cli --version "^1.0.0"

      - name: Build GUI
        run: cargo tauri build

      - name: Create Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          name: RLBotGUI Rust port ${{steps.version_check_staging.outputs.releaseVersion}}
          body: ${{ github.event.head_commit.message }}
          draft: false
          files: |
            ./**/target/**/*.msi
            ./**/target/**/*.msi.zip
